---
title: "Testat 1 Aufgabe 1: Histogramm"
output: html_notebook
---

## 1.1

```{r}
myhistogram = function(x, n=1, min=NA, max=NA) {
    sorted = sort(x)
    min=ifelse(is.na(min), min(x), min)
    max=ifelse(is.na(max), max(x) + 1, max)

    sortedNumbers = sorted[sorted >= min]
    sortedNumbers = sortedNumbers[sortedNumbers < max]

    outside = sorted[sorted < min]
    outside = sorted[sorted > max]

    if (length(outside) > 0) {
        warning(paste0('Zahlen außerhalb von Intervallgrenzen: ', paste(outside, collapse = ", ")))
    }

    borders = seq(min, max, length.out=n+1)
    counts = sapply(seq(from=1, to=n), function(e) {
        min = borders[e]
        max = borders[e+1]

        intervall = sortedNumbers[sortedNumbers >= min]
        intervall = intervall[intervall < max]

        length(intervall)
    })

    list(borders, counts)
}
```

## 1.2
### 1.2.1
```{r}
x = seq(-5, 6, by = 1 / 3)
myhistogram(x, n = 10, min = -5, max = 6)
```
### 1.2.2
```{r}
x = seq(-5, 6, by = 1 / 3)
myhistogram(x, n = 5, min = -10, max = 10)
```
### 1.2.3
```{r}

```
### 1.2.4
```{r}

```
### 1.2.5
```{r}

```