---
title: "Testat 1 Aufgabe 3: Covid19: Impffortschritt in Deutschland"
output: html_notebook
---

## 3.1
```{r}
vaccFile = url('https://impfdashboard.de/static/data/germany_vaccinations_timeseries_v2.tsv')
delivFile = url('https://impfdashboard.de/static/data/germany_deliveries_timeseries_v2.tsv')
vaccStateFile = url('https://impfdashboard.de/static/data/germany_vaccinations_by_state.tsv')

vacc = data.frame(read.table(vaccFile, sep='\t', header=TRUE))
deliv = data.frame(read.table(delivFile, sep='\t', header=TRUE))
vaccState = data.frame(read.table(vaccStateFile, sep='\t', header=TRUE))
```
```{r}
vacc$date = as.Date(vacc$date, '%Y-%m-%d')
deliv$date = as.Date(deliv$date, '%Y-%m-%d')

head(vacc |> dplyr::select(1:3), 3)
head(deliv |> dplyr::select(1:3), 3)
head(vaccState |> dplyr::select(1:3), 3)
```
## 3.2
### 3.2.1
```{r}
library(dplyr)
library(tidyr)
vacc_reduced = as_tibble(vacc) |> dplyr::select(1, 3, 8, 13, 18, 23, 28) |> rename(Datum = date)
firstRow = head(vacc_reduced, 1)
vacc2 = vacc_reduced |> mutate_at(.vars = 2:7, .funs = list(~ . -lag(.)))
vacc2[1,] = firstRow

vacc2 = vacc2 |> pivot_longer(
    cols = c(2:7),
    names_to = 'Hersteller',
    values_to = 'Impfdosen pro Tag',
    names_pattern = 'dosen_(\\w+)_kumulativ'
  ) |>
  arrange(Datum, Hersteller)

knitr::kable(tail(vacc2, 10))

```
### 3.2.2
```{r}
library(ggplot2)

ggplot(vacc2) +
  geom_line(aes(x=Datum, y=`Impfdosen pro Tag`, group=Hersteller, color=Hersteller))

```
## 3.3
```{r}
deliv2 = deliv |> group_by(date, impfstoff) |>
  mutate(Liefermenge = sum(dosen)) |>
  dplyr::select(1, 2, 7) |>
  distinct(date, impfstoff, Liefermenge) |>
  mutate(impfstoff = case_when(impfstoff == 'comirnaty' ~ 'biontech', TRUE ~ impfstoff))

vacc_joined = vacc2 |> inner_join(deliv2, c('Datum' = 'date', 'Hersteller' = 'impfstoff'))

ggplot(vacc_joined) +
  geom_line(aes(x=Datum, y=`Impfdosen pro Tag`, color='red'), linetype = 'solid') +
  geom_line(aes(x=Datum, y=Liefermenge, color='blue'), linetype = 'dashed') +
  facet_wrap(~ Hersteller) +
  labs(title = 'Liefermenge und Impfungen', col = 'Impfdosen')
```